
stages:
  - build

.build: &build
  stage: build
  script:
    - 'bin/build.sh $TARGET'
    - 'bin/push.sh $TARGET'
    - 'bin/cleanup.sh $TARGET'
  only:
    - /^master$/
  tags:
    - shell

.build-php: &build-php
  stage: build
  script:
    - 'bin/build.sh php $TYPE $VERSION'
    - 'bin/push.sh php'
    - 'bin/cleanup.sh php'
  only:
    - /^master$/
  tags:
    - shell

before_script:
  - docker-compose pull

# build apache
build-apache:
  variables:
    TARGET: apache
  <<: *build

# build elasticsearch
build-elasticsearch:
  variables:
    TARGET: elasticsearch
  <<: *build

# build mysql
build-mysql:
  variables:
    TARGET: mysql
  <<: *build

# build percona
build-percona:
  variables:
    TARGET: percona
  <<: *build

# build php
build-php-cli-7.3:
  variables:
    TYPE: cli
    VERSION: 7.3
  <<: *build-php

build-php-cli-7.4:
  variables:
    TYPE: cli
    VERSION: 7.4
  <<: *build-php

build-php-cli-8.0:
  variables:
    TYPE: cli
    VERSION: 8.0
  <<: *build-php

build-php-cli-8.1:
  variables:
    TYPE: cli
    VERSION: 8.1
  <<: *build-php

build-php-cli-8.2:
  variables:
    TYPE: cli
    VERSION: 8.2
  <<: *build-php
build-php-fpm-7.3:
  variables:
    TYPE: fpm
    VERSION: 7.3
  <<: *build-php

build-php-fpm-7.4:
  variables:
    TYPE: fpm
    VERSION: 7.4
  <<: *build-php

build-php-fpm-8.0:
  variables:
    TYPE: fpm
    VERSION: 8.0
  <<: *build-php

build-php-fpm-8.1:
  variables:
    TYPE: fpm
    VERSION: 8.1
  <<: *build-php

build-php-fpm-8.2:
  variables:
    TYPE: fpm
    VERSION: 8.2
  <<: *build-php

# build python
build-python:
  variables:
    TARGET: python
  <<: *build

# build selenium-side-runner
build-selenium-side-runner:
  variables:
    TARGET: selenium-side-runner
  <<: *build

# build solr
build-solr:
  variables:
    TARGET: solr
  <<: *build

# build ssh
build-ssh:
  variables:
    TARGET: ssh
  <<: *build

# build node
build-node:
  variables:
    TARGET: node
  <<: *build
