
stages:
  - build

.build: &build
  stage: build
  script:
    - 'bin/build.sh $TARGET'
    - 'bin/push.sh $TARGET'
    - 'bin/cleanup.sh $TARGET'
  only:
    - /^master$/
  tags:
    - shell

before_script:
  - docker-compose pull

# build apache
build-apache:
  variables:
    TARGET: apache
  <<: *build

# build elasticsearch
build-elasticsearch:
  variables:
    TARGET: elasticsearch
  <<: *build

# build mysql
build-mysql:
  variables:
    TARGET: mysql
  <<: *build

# build percona
build-percona:
  variables:
    TARGET: percona
  <<: *build

# build php
build-php:
  variables:
    TARGET: php
  <<: *build

# build python
build-python:
  variables:
    TARGET: python
  <<: *build

# build selenium-side-runner
build-selenium-side-runner:
  variables:
    TARGET: selenium-side-runner
  <<: *build

# build solr
build-solr:
  variables:
    TARGET: solr
  <<: *build

# build ssh
build-ssh:
  variables:
    TARGET: ssh
  <<: *build

# build node
build-node:
  variables:
    TARGET: node
  <<: *build
