version: "3"

services:

  #
  # ssh for port forwarding
  #
  ssh:
    container_name: ssh
    build:
      context: .
      dockerfile: docker/ssh/Dockerfile

  #
  # latest php 7.3
  #
  php-fpm-7.3:
    container_name: php-fpm-7.3
    build:
      context: .
      dockerfile: docker/php-fpm/7.3/Dockerfile

  php-cli-7.3:
    container_name: php-cli-7.3
    build:
      context: .
      dockerfile: docker/php-cli/7.3/Dockerfile
    tty: true
  #
  # latest php 7.4
  #
  php-fpm-7.4:
    container_name: php-fpm-7.4
    build:
      context: .
      dockerfile: docker/php-fpm/7.4/Dockerfile

  php-cli-7.4:
    container_name: php-cli-7.4
    build:
      context: .
      dockerfile: docker/php-cli/7.4/Dockerfile
    tty: true
  #
  # latest php 8.0
  #
  php-fpm-8.0:
    container_name: php-fpm-8.0
    build:
      context: .
      dockerfile: docker/php-fpm/8.0/Dockerfile

  php-cli-8.0:
    container_name: php-cli-8.0
    build:
      context: .
      dockerfile: docker/php-cli/8.0/Dockerfile
    tty: true
  #
  # latest php 8.1
  #
  php-fpm-8.1:
    container_name: php-fpm-8.1
    build:
      context: .
      dockerfile: docker/php-fpm/8.1/Dockerfile

  php-cli-8.1:
    container_name: php-cli-8.1
    build:
      context: .
      dockerfile: docker/php-cli/8.1/Dockerfile
    tty: true

  #
  # mysql 5.5.62
  #
  mysql-5.5:
      container_name: mysql-5.5
      environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
      build:
        context: .
        dockerfile: docker/mysql/5.5/Dockerfile

  #
  # mysql 5.6.43
  #
  mysql-5.6:
    container_name: mysql-5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mysql/5.6/Dockerfile

  #
  # mysql 5.7.25
  #
  mysql-5.7:
    container_name: mysql-5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mysql/5.7/Dockerfile

  #
  # mysql 8.0.15
  #
  mysql-8.0:
    container_name: mysql-8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mysql/8.0/Dockerfile

  #
  # percona 5.7.25
  #
  percona-5.7:
    container_name: percona-5.7
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/percona/5.7/Dockerfile

  #
  # percona 8.0.15
  #
  percona-8.0:
    container_name: percona-8.0
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/percona/8.0/Dockerfile

  #
  # mariadb 10.2.23
  #
  mariadb-10.2:
    container_name: mariadb-10.2
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mariadb/10.2/Dockerfile

  #
  # mariadb 10.3.13
  #
  mariadb-10.3:
    container_name: mariadb-10.3
    build:
      context: .
      dockerfile: docker/mariadb/10.3/Dockerfile

  #
  # mariadb 10.4.3
  #
  mariadb-10.4:
    container_name: mariadb-10.4
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mariadb/10.4/Dockerfile

  mariadb-10.5:
    container_name: mariadb-10.5
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mariadb/10.5/Dockerfile

  mariadb-10.6:
    container_name: mariadb-10.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mariadb/10.6/Dockerfile

  mariadb-10.7:
    container_name: mariadb-10.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    build:
      context: .
      dockerfile: docker/mariadb/10.7/Dockerfile
  #
  # apache 2.4.39
  #
  apache-2.4:
    container_name: apache-2.4
    build:
      context: .
      dockerfile: docker/apache/2.4/Dockerfile

  selenium-side-runner:
    container_name: selenium-side-runner
    build:
      context: .
      dockerfile: docker/selenium-side-runner/Dockerfile
    tty: true

  elasticsearch-5.6:
    container_name: elasticsearch-5.6
    build:
      context: .
      dockerfile: docker/elasticsearch/5.6/Dockerfile

  elasticsearch-6.4:
    container_name: elasticsearch-6.4
    build:
      context: .
      dockerfile: docker/elasticsearch/6.4/Dockerfile

  elasticsearch-6.8:
    container_name: elasticsearch-6.8
    build:
      context: .
      dockerfile: docker/elasticsearch/6.8/Dockerfile

  elasticsearch-7.1:
    container_name: elasticsearch-7.1
    build:
      context: .
      dockerfile: docker/elasticsearch/7.1/Dockerfile

  elasticsearch-7.3:
    container_name: elasticsearch-7.3
    build:
      context: .
      dockerfile: docker/elasticsearch/7.3/Dockerfile

  elasticsearch-7.6:
    container_name: elasticsearch-7.6
    build:
      context: .
      dockerfile: docker/elasticsearch/7.3/Dockerfile

  elasticsearch-7.10:
    container_name: elasticsearch-7.10
    build:
      context: .
      dockerfile: docker/elasticsearch/7.10/Dockerfile

  elasticsearch-7.16:
    container_name: elasticsearch-7.16
    build:
      context: .
      dockerfile: docker/elasticsearch/7.16/Dockerfile
  node-11:
    container_name: node-11
    build:
      context: .
      dockerfile: docker/node/11/Dockerfile

  node-12:
    container_name: node-12
    build:
      context: .
      dockerfile: docker/node/16/Dockerfile

  node-14:
    container_name: node-14
    build:
      context: .
      dockerfile: docker/node/16/Dockerfile

  node-16:
    container_name: node-16
    build:
      context: .
      dockerfile: docker/node/16/Dockerfile

  node-17:
    container_name: node-17
    build:
      context: .
      dockerfile: docker/node/17/Dockerfile

  node-18:
    container_name: node-18
    build:
      context: .
      dockerfile: docker/node/18/Dockerfile

  python-3.10:
    container_name: python-3.10
    build:
      context: .
      dockerfile: docker/python/3.10/Dockerfile

  solr-7.7:
    container_name: solr-7.7
    build:
      context: .
      dockerfile: docker/solr/7.7/Dockerfile

  solr-8.9:
    container_name: solr-8.9
    build:
      context: .
      dockerfile: docker/solr/8.9/Dockerfile

