FROM docker.elastic.co/elasticsearch/elasticsearch:6.8.23

LABEL de.sandstein.dde="elasticsearch"

COPY files/usr/local/bin/modify-user-ids /usr/local/bin
COPY files/usr/local/bin/modify-elasticsearch-entrypoint /usr/local/bin
